#ifndef CYCAMORE_SRC_VERSION_H_
#define CYCAMORE_SRC_VERSION_H_

#define CYCAMORE_VERSION_MAJOR 1
#define CYCAMORE_VERSION_MINOR 5
#define CYCAMORE_VERSION_MICRO 5
#define CYCAMORE_VERSION "1.5.5-43-gc7506f19"

#endif  // CYCAMORE_SRC_VERSION_H_
